# Generated by Django 6.0 on 2026-02-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.BigIntegerField()),
                ('Password', models.CharField(max_length=20)),
                ('CPassword', models.CharField(max_length=20, null=True)),
                ('Photo', models.ImageField(upload_to='image')),
                ('Audio', models.FileField(upload_to='audio')),
                ('Video', models.FileField(upload_to='video')),
                ('Resume', models.FileField(upload_to='document')),
                ('City', models.CharField(max_length=20)),
                ('Qualification', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
            ],
        ),
    ]
