# Generated by Django 6.0 on 2026-02-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='Departments',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
