# Generated by Django 6.0 on 2026-02-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dep_name', models.CharField(max_length=20)),
                ('Dep_desc', models.CharField(max_length=20)),
                ('Dep_head', models.CharField(max_length=20)),
            ],
        ),
    ]
