# Generated by Django 6.0 on 2026-02-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Departments', models.CharField(max_length=40)),
                ('Query', models.TextField()),
                ('Status', models.CharField(default='pending')),
            ],
        ),
    ]
