# Generated by Django 6.0 on 2026-02-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='Reply',
            field=models.TextField(null=True),
        ),
    ]
