# Generated by Django 6.0 on 2026-02-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_query_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Status',
            field=models.CharField(default=False),
        ),
    ]
