# Generated by Django 6.0 on 2026-03-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_query_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('item_desc', models.CharField(max_length=40)),
                ('item_price', models.IntegerField()),
                ('item_image', models.ImageField(upload_to='image')),
                ('item_color', models.CharField(max_length=20)),
                ('item_category', models.CharField(max_length=40)),
                ('item_quanity', models.IntegerField()),
            ],
        ),
    ]
